/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_autch_android_pceplayer_PMDPlayerThread */

#ifndef _Included_net_autch_android_pceplayer_PMDPlayerThread
#define _Included_net_autch_android_pceplayer_PMDPlayerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef net_autch_android_pceplayer_PMDPlayerThread_MIN_PRIORITY
#define net_autch_android_pceplayer_PMDPlayerThread_MIN_PRIORITY 1L
#undef net_autch_android_pceplayer_PMDPlayerThread_NORM_PRIORITY
#define net_autch_android_pceplayer_PMDPlayerThread_NORM_PRIORITY 5L
#undef net_autch_android_pceplayer_PMDPlayerThread_MAX_PRIORITY
#define net_autch_android_pceplayer_PMDPlayerThread_MAX_PRIORITY 10L
/*
 * Class:     net_autch_android_pceplayer_PMDPlayerThread
 * Method:    muslib_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_pceplayer_PMDPlayerThread_muslib_1init
  (JNIEnv *, jclass);

/*
 * Class:     net_autch_android_pceplayer_PMDPlayerThread
 * Method:    muslib_load_from_file
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_autch_android_pceplayer_PMDPlayerThread_muslib_1load_1from_1file
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_autch_android_pceplayer_PMDPlayerThread
 * Method:    muslib_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_pceplayer_PMDPlayerThread_muslib_1start
  (JNIEnv *, jclass);

/*
 * Class:     net_autch_android_pceplayer_PMDPlayerThread
 * Method:    muslib_render
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_net_autch_android_pceplayer_PMDPlayerThread_muslib_1render
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     net_autch_android_pceplayer_PMDPlayerThread
 * Method:    muslib_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_pceplayer_PMDPlayerThread_muslib_1close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
