/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_autch_android_pceplayer_MusLibInterface */

#ifndef _Included_net_autch_android_pceplayer_MusLibInterface
#define _Included_net_autch_android_pceplayer_MusLibInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_autch_android_pceplayer_MusLibInterface
 * Method:    muslib_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_pceplayer_MusLibInterface_muslib_1init
  (JNIEnv *, jclass);

/*
 * Class:     net_autch_android_pceplayer_MusLibInterface
 * Method:    muslib_load_from_file
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_autch_android_pceplayer_MusLibInterface_muslib_1load_1from_1file
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_autch_android_pceplayer_MusLibInterface
 * Method:    muslib_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_pceplayer_MusLibInterface_muslib_1start
  (JNIEnv *, jclass);

/*
 * Class:     net_autch_android_pceplayer_MusLibInterface
 * Method:    muslib_render
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_net_autch_android_pceplayer_MusLibInterface_muslib_1render
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     net_autch_android_pceplayer_MusLibInterface
 * Method:    muslib_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_pceplayer_MusLibInterface_muslib_1close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
